#!/usr/bin/env python3
"""Synchronize the GitHub Pages front page with the canonical strategy guide.

No third-party packages are required. GitHub Pages renders the generated
Markdown with its native Jekyll build. Run with --check to detect a stale page.
"""

import argparse
import hashlib
import json
from pathlib import Path
import posixpath
import re
from urllib.parse import quote, unquote, urlsplit, urlunsplit


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "original/strategy-guide.md"
DESTINATION = ROOT / "docs/index.md"
REPOSITORY = "https://github.com/PeterEFrancis/solitaire-research"
BRANCH = "main"


def repository_link(destination, image=False):
    """Resolve a guide-relative link to a stable repository-relative location."""
    match = re.match(r"^<([^>]+)>(.*)$", destination)
    if match is None:
        match = re.match(r"^(\S+)(.*)$", destination)
    if match is None:
        return destination
    target, suffix = match.groups()
    parsed = urlsplit(target)
    if parsed.scheme or parsed.netloc or target.startswith("#"):
        return destination
    if not parsed.path:
        return destination
    if parsed.path.startswith("/"):
        raise ValueError(f"Use a guide-relative path, not an absolute local path: {target}")
    path = posixpath.normpath(posixpath.join("original", unquote(parsed.path)))
    if path == ".." or path.startswith("../"):
        raise ValueError(f"Link escapes the repository: {target}")
    if not (ROOT / path).exists():
        raise ValueError(f"Guide link does not exist: {target} (resolved as {path})")
    base = ("https://raw.githubusercontent.com/PeterEFrancis/solitaire-research/"
            if image else REPOSITORY + "/blob/")
    absolute = base + BRANCH + "/" + quote(path, safe="/")
    linked = urlsplit(absolute)
    return urlunsplit((linked.scheme, linked.netloc, linked.path, parsed.query, parsed.fragment)) + suffix


def transform(source):
    title_match = re.search(r"^#\s+(.+?)\s*$", source, flags=re.MULTILINE)
    if title_match is None:
        raise ValueError("The canonical guide must have a level-one title")
    title = title_match.group(1)
    toc = []
    used_ids = set()
    output = []
    fence = None
    for line in source.splitlines():
        fence_match = re.match(r"^\s*(`{3,}|~{3,})", line)
        if fence_match:
            token = fence_match.group(1)
            if fence is None:
                fence = token
            elif token[0] == fence[0] and len(token) >= len(fence):
                fence = None
            output.append(line)
            continue
        if fence is not None:
            output.append(line)
            continue

        # Give headings explicit IDs so navigation does not depend on a
        # Markdown renderer's punctuation or duplicate-heading conventions.
        heading = re.match(r"^(#{2,3})\s+(.+?)\s*$", line)
        if heading:
            level, text = heading.groups()
            existing_id = re.search(r"\s*\{#([\w-]+)\}\s*$", text)
            if existing_id:
                anchor = existing_id.group(1)
                text = text[:existing_id.start()].strip()
            else:
                stem = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "section"
                anchor = stem
                suffix = 2
                while anchor in used_ids:
                    anchor = f"{stem}-{suffix}"
                    suffix += 1
                line = f"{level} {text} {{#{anchor}}}"
            if anchor in used_ids:
                raise ValueError(f"Duplicate explicit heading ID: {anchor}")
            used_ids.add(anchor)
            if len(level) == 2:
                toc.append({"title": re.sub(r"[`*_]", "", text), "id": anchor})

        line = re.sub(
            r"(!?)\[([^\]\n]*)\]\(([^)\n]+)\)",
            lambda match: f"{match[1]}[{match[2]}]({repository_link(match[3], bool(match[1]))})",
            line,
        )
        reference = re.match(r"^(\s*\[[^\]]+\]:\s*)(.+)$", line)
        if reference:
            line = reference[1] + repository_link(reference[2])
        output.append(line)

    metadata = [
        "---", "layout: default", "title: " + json.dumps(title, ensure_ascii=False),
        'source_path: "original/strategy-guide.md"',
        "source_sha256: " + hashlib.sha256(source.encode()).hexdigest(), "toc:",
    ]
    for item in toc:
        metadata.extend(["  - title: " + json.dumps(item["title"], ensure_ascii=False),
                         "    id: " + json.dumps(item["id"])])
    metadata.extend(["---", "", "<!-- Generated by scripts/build_pages.py; edit original/strategy-guide.md. -->", ""])
    return "\n".join(metadata + output).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit nonzero if the generated page is stale")
    args = parser.parse_args()
    expected = transform(SOURCE.read_text(encoding="utf-8"))
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
            parser.exit(1, "GitHub Pages content is stale. Run python3 scripts/build_pages.py.\n")
        print("GitHub Pages front page matches original/strategy-guide.md.")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(expected, encoding="utf-8")
        print("Updated docs/index.md from original/strategy-guide.md.")


if __name__ == "__main__":
    main()
